import React from 'react'
import Footer from '../components/Footer'
import ProductCardContainer from '../components/ProductCardContainer'
import AdvertisementCard from '../components/AdvertisementCard'
import BrandAdSection from '../components/BrandAdSection'
import Slideshow from '../components/Slideshow'
import Header from '../components/Header'

const Home = () => {
    const productData = {
        "name": "Deal of the Day",
        "id": 4,
        "items": [
            {
                "pid": "355",
                "user_id": "15",
                "seller_id": "0",
                "store_id": "0",
                "productid": "5d1dd6f3b1ab9b1013800551f7329be6",
                "product_name": "Ring Light, for Photo and Video with 7 Feet Tripod Stand Compatible with Camera and Smartphones (10 Inch LED Ring Light)",
                "product_slug": "Ring-Light-for-Photo-and-Video-with-7-Feet-Tripod-Stand-Compatible-with-Camera-and-Smartphones-10-Inch-LED-Ring-Light",
                "product_sku": "Ring Light 10",
                "product_price": "2999",
                "product_sale_price": "799",
                "product_stock": "91",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>YOU WANT - A Portable, Most Smartphone Compatible, LED Camera Light. The Mini Ring Light is easy to use with the adjustable tripod stand. You need - a ring light with 3 lighting modes: white, warm yellow, warm yellow + white. and 11 modes each with adjustable brightness for perfect lighting in a variety of conditions. You Desire - Single product with multiple uses such as video filming, photography, selfie as well as table or floor lighting. Smartphones these days are great for taking pictures and shooting videos because it is so convenient. But, do you find it difficult to find the perfect lighting to take photos or videos: Do you always find it difficult to find the right place to hold your cellphone while shooting videos or taking photos: If so, with a tripod Our Ring Light is the perfect solution for you. It has many different functions and benefits to meet what you need: 360&deg; Rotation Ring Light Head 360&deg; Rotation Universal Phone Holder Adjustable Trip Stand 13.8'' - 39.4'' Dimmable LED Light (3 Light Modes, 11 Adjustable Brightness) Plus powered USB port. Best for YouTube Videos, Blog Shoot Live Stream/Makeup - 10 Inch, selfi, instagram reel etc.</p>",
                "product_images": "assets/product_image/2a0b89ff59d66bf634a63ccc96f9aea9.png",
                "add_info": "<p>Generic Name : Selfie Ring Light with Stand</p>\r\n<p>&nbsp;</p>\r\n<p>Ring Light Size : 10\"</p>\r\n<p>&nbsp;</p>\r\n<p>Tripods Stand : 7f</p>\r\n<p>&nbsp;</p>\r\n<p>Light Mode : 3 Colour</p>\r\n<p>&nbsp;</p>\r\n<p>In the Box : 1N Selfie Ring Light, 1N Tripod Stand</p>",
                "add_information": "[{\"title\":\"Generic Name\",\"description\":\"Selfie Ring Light with Stand\"},{\"title\":\"Ring Light Size\",\"description\":\"10'\"},{\"title\":\"Tripods Stand\",\"description\":\"7f\"},{\"title\":\"Light Mode\",\"description\":\"3 Colour\"},{\"title\":\"In the Box\",\"description\":\"1N Selfie Ring Light, 1N Tripod Stand\"}]",
                "return_policy": "<p><strong>Warranty Summary :</strong>&nbsp;7 Days Replacement Warranty. If you have received a damaged or defective product or if it is not as described, you can raise a replacement request on the Website/Mobile site within&nbsp;7 days of receiving the product.</p>\r\n<p><br /><strong>Service Type :</strong>&nbsp;7 Days Replacement Policy.</p>\r\n<p><br /><strong>Covered in Warranty :</strong>&nbsp;<strong>(Warranty of the Product is Limited to Manufacturing Defects only.)</strong></p>\r\n<p><br /><strong>Not Covered in Warranty:</strong>&nbsp;Warranty does not Cover any Physical Damage.</p>",
                "product_category": "102,133",
                "product_options": "",
                "size": "",
                "color": "",
                "brand": "0",
                "product_upload_date": "2021-07-20 06:17:46",
                "product_tag": "selfi lights,trypods,power bank,data cable,uoons,mi,samsung,oppo,vivo,realme",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "73.36",
                "end_date": "2021-09-30",
                "start_date": "2021-07-27",
                "republic_day": "0",
                "shipping_charges": "",
                "deal_of_the_day": "1",
                "cash_on_delivary": "0",
                "salient_features": "<ul>\r\n<li>3 Colors Lighting Mode</li>\r\n<li>11 Level Brightness</li>\r\n<li>360 degree adjustable</li>\r\n<li>Mostly devices supported</li>\r\n</ul>",
                "product_salient": "",
                "freqvently_bought": "199,242,355",
                "product_services": "1,2,4",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "Ring Light, for Photo and Video with 7 Feet Tripod Stand Compatible with Camera and Smartphones (10 Inch LED Ring Light)",
                "meta_decs": "Ring Light, for Photo and Video with 7 Feet Tripod Stand Compatible with Camera and Smartphones (10 Inch LED Ring Light), ring light with tripod stand under 1000, best selfie ring light with tripod stand & cell phone holder, selfie ring light price indore, India, delhi",
                "live": "0"
            },
            {
                "pid": "636",
                "user_id": "15",
                "seller_id": "0",
                "store_id": "0",
                "productid": "29577caec81c7c31787b9f8d6a75c2e6",
                "product_name": "Haier 6.5 kg Fully-Automatic Top Loading Washing Machine HWM65-707NZP (Silver Grey)",
                "product_slug": "Haier-65-kg-Fully-Automatic-Top-Loading-Washing-Machine-HWM65-707NZP-Silver-Grey",
                "product_sku": " HWM65-707NZP",
                "product_price": "21200",
                "product_sale_price": "18100",
                "product_stock": "87",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<h4 class=\"a-spacing-mini\">Oceanus Wave Drum</h4>\r\n<p>This cubical shaped stainless steel drum provides a stronger water flow that gently cleans and effectively washes dirty laundry with lesser abrasion.</p>\r\n<p>&nbsp;</p>\r\n<h4 class=\"a-spacing-mini\">Double Magic Filter</h4>\r\n<p>With continuous washing, clothes produce lint. The double magic filter helps remove the lint produced from clothes during a wash cycle which results in cleaner clothes.</p>\r\n<p>&nbsp;</p>\r\n<h4 class=\"a-spacing-mini\">Deep Clean Pulsator</h4>\r\n<p>Clean heavy and large clothes easier as this washing machine features a strong pulsator that provides a powerful motion. It also supports gentle motion to clean delicate fabrics.</p>\r\n<p>&nbsp;</p>\r\n<h4 class=\"a-spacing-mini\">8 Wash Programs</h4>\r\n<p>Choose your desired wash cycle from delicate fabrics to tough clothes from 8 different wash cycles. Specially designed with an ariel top matic feature for whiter whites.</p>\r\n<p>&nbsp;</p>\r\n<h4 class=\"a-spacing-mini\">Near Zero Pressure</h4>\r\n<p>Wash and rinse your dirty laundry even with low water pressure. The washing machines can function efficiently with a water pressure of 0.001-0.002 MPA.</p>\r\n<p>&nbsp;</p>\r\n<h4 class=\"a-spacing-mini\">Jet Stream Technology</h4>\r\n<p>Equipped with high pressure water jet technology, this allows the water to spurt out from below and from above, giving you a 4-way uniform washing</p>",
                "product_images": "assets/product_image/44ce7c7a51b8c96df9cd83f11aac4aa4.jpg",
                "add_info": "<p>Brand : Haier</p>\r\n<p>&nbsp;</p>\r\n<p>Model : HWM65-707NZP&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>Capacity : 6.5kg</p>\r\n<p>&nbsp;</p>\r\n<p>Rotational Speed : 800 RPH</p>\r\n<p>&nbsp;</p>\r\n<p>Special Features : &lrm;Transparent Lid, LED display, Double Magic Filter</p>\r\n<p>&nbsp;</p>\r\n<p>Control Console : Fully Automatic</p>\r\n<p>&nbsp;</p>\r\n<p>Material : Plastic&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>In the box : 1 Washing Machine, 1 User Manual, 1 Inlet hose, Tapping Screw and Warranty Card</p>\r\n<p>&nbsp;</p>\r\n<p>Colour : Silver Grey</p>\r\n<p>&nbsp;</p>\r\n<p>Manufacturer : Haier</p>\r\n<p>&nbsp;</p>\r\n<p>Country of Origin : India</p>",
                "add_information": "[{\"title\":\"Brand\",\"description\":\"Haier\"},{\"title\":\"Model\",\"description\":\"HWM65-707NZP\"},{\"title\":\"Capacity\",\"description\":\"6.5kg\"},{\"title\":\"Rotational Speed\",\"description\":\"800 RPH\"},{\"title\":\"Special Features\",\"description\":\"&lrm;Transparent Lid, LED display, Double Magic Filter\"},{\"title\":\"Control Console\",\"description\":\"Fully Automatic\"},{\"title\":\"Material\",\"description\":\"Plastic\"},{\"title\":\"In the box\",\"description\":\"1 Washing Machine, 1 User Manual, 1 Inlet hose, Tapping Screw and Warranty Card\"},{\"title\":\"Colour\",\"description\":\"Silver Grey\"},{\"title\":\"Manufacturer\",\"description\":\"Haier\"},{\"title\":\"Country of Origin\",\"description\":\"India\"}]",
                "return_policy": "<p>Warranty Summary :&nbsp;7 Days Replacement Warranty. If you have received a damaged or defective product or if it is not as described, you can raise a replacement request on the Website/Mobile site within&nbsp;7 days of receiving the product.</p>\r\n<p><br />Service Type :&nbsp;7 Days Replacement Policy.</p>\r\n<p><br />Covered in Warranty :&nbsp;<span class=\"a-list-item\">2 years on product, 10 years on motor warranty </span>of the Product is Limited to Manufacturing Defects only.(For any warranty related issues, please contact the Customer Support -Haier Careline:&nbsp;<br />1800-419-9999 1800-102-9999 Service time: 7*24H Monday to Sunday)</p>\r\n<p><br />Not Covered in Warranty: Warranty does not Cover any Physical Damage</p>",
                "product_category": "126,187,241,252",
                "product_options": "",
                "size": "",
                "color": "",
                "brand": "37",
                "product_upload_date": "2021-09-15 08:05:44",
                "product_tag": "Haier 6.5 kg Fully-Automatic Top Loading Washing Machine,Top Loading Washing Machine,Washing Machine,Haier ,HWM65-707NZP,Haier 6.5 kg Fully-Automatic Top Loading Washing Machine (HWM65-707NZP",
                "type": "0",
                "best_selling": "1",
                "best_selling_color": "1",
                "feat_prod": "0",
                "discount": "14.62",
                "end_date": "2021-11-05",
                "start_date": "2021-10-05",
                "republic_day": "0",
                "shipping_charges": "",
                "deal_of_the_day": "1",
                "cash_on_delivary": "1",
                "salient_features": "<ul>\r\n<li>Easy to use</li>\r\n<li>Capacity 6.5 kg</li>\r\n<li>800 Spin RPM</li>\r\n<li>8 wash programs</li>\r\n<li>&nbsp;Near Zero Pressure</li>\r\n</ul>",
                "product_salient": "",
                "freqvently_bought": "649,572,636",
                "product_services": "1,2,3,5,7",
                "gst": "18",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "Haier 6.5 kg Fully-Automatic Top Loading Washing Machine HWM65-707NZP (Silver Grey)",
                "meta_decs": "Haier 6.5 kg Fully-Automatic Top Loading Washing Machine HWM65-707NZP (Silver Grey),Haier 6.5 kg Fully-Automatic Top Loading Washing Machine (HWM65-707NZP, Top Load Automatic  HWM65-707NZP",
                "live": "0"
            },
            {
                "pid": "1085",
                "user_id": "15",
                "seller_id": "0",
                "store_id": "0",
                "productid": "55c6f96575e389f856249780a1f9c55e",
                "product_name": "Smart Micro USB OTG Adapter (Pack of 2) Multi color, Available with Prepaid order only",
                "product_slug": "Smart-Micro-USB-OTG-Adapter-Pack-of-2-Multi-color",
                "product_sku": "Smart Micro USB P4",
                "product_price": "125",
                "product_sale_price": "12",
                "product_stock": "957",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>Compatible Male Connectors, Compatible Female Connectors, Micro USB OTG Adapter</p>",
                "product_images": "assets/product_image/1df7e084c0912f0ebab997312568017d.jpg",
                "add_info": "<p>Brand : TP</p>\r\n<p>&nbsp;</p>\r\n<p>Model : Mini22</p>\r\n<p>&nbsp;</p>\r\n<p>Color : Multi Color</p>\r\n<p>&nbsp;</p>\r\n<p>Port Type : Micro USB</p>\r\n<p>&nbsp;</p>\r\n<p>Compatible Male Connectors : MP3 Player, Mobile, Tablet, Camera</p>\r\n<p>&nbsp;</p>\r\n<p>Compatible Female Connectors : Pen Drive</p>\r\n<p>&nbsp;</p>\r\n<p>In the Box : 4 Adapter</p>",
                "add_information": "[{\"title\":\"Brand\",\"description\":\"TP\"},{\"title\":\"Model\",\"description\":\"Mini22\"},{\"title\":\"Color\",\"description\":\"Multi Color\"},{\"title\":\"Port Type\",\"description\":\"Micro USB\"},{\"title\":\"Compatible Male Connectors\",\"description\":\"MP3 Player, Mobile, Tablet, Camera\"},{\"title\":\"Compatible Female Connectors\",\"description\":\"Pen Drive\"},{\"title\":\"In the Box\",\"description\":\"4 Adapter\"}]",
                "return_policy": "<p><strong>Not Covered in Warranty</strong></p>",
                "product_category": "102,139",
                "product_options": "",
                "size": "",
                "color": "",
                "brand": "11",
                "product_upload_date": "2024-01-03 12:14:40",
                "product_tag": "otg adapter,uoons,tp troops",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "90.4",
                "end_date": "2024-02-17",
                "start_date": "2024-01-03",
                "republic_day": "0",
                "shipping_charges": "",
                "deal_of_the_day": "1",
                "cash_on_delivary": "1",
                "salient_features": "<ul>\r\n<li>Compatible Male Connectors</li>\r\n<li>Compatible Female Connectors</li>\r\n<li>Micro USB OTG Adapter</li>\r\n</ul>",
                "product_salient": "",
                "freqvently_bought": "1085,1086,1087",
                "product_services": "1,2,5,6",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "Smart Micro USB OTG Adapter  (Pack of 4) Multi color",
                "meta_decs": "Smart Micro USB OTG Adapter  (Pack of 4) Multi color",
                "live": "0"
            },
            {
                "pid": "1376",
                "user_id": null,
                "seller_id": "83",
                "store_id": "38",
                "productid": "118e6584050779c9cc99aa39c7de4542",
                "product_name": "Denzcart Spike 10 min Fly Time| 50m Range | Non-Camera Nano Drone ",
                "product_slug": "denzcart-spike-10-min-fly-time-50m-range-non-camera-nano-drone",
                "product_sku": "Drone-Non-Camera",
                "product_price": "14599",
                "product_sale_price": "9999",
                "product_stock": "0",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>Unbreakable&nbsp;</p>\r\n<p>6-axis IMU Stabilization</p>\r\n<p>Wi-fi control via app</p>\r\n<p>Suitable Above 14 year age</p>\r\n<p>Unbreakable Drone</p>\r\n<p>Battery Charging Time 40 Mintutes</p>\r\n<p>50 Meter Range&nbsp;</p>\r\n<p>Flight Time 8-10 Min</p>\r\n<p>6 Month Warrenty</p>\r\n<p>Camera- No</p>\r\n<p>Battery- 800 mAh</p>",
                "product_images": "assets/product_image/db9eeeefa2c3e154ae6ced9d2d91dc78.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"Denzcart\"},{\"name\":\"Model\",\"value\":\"Spk-NC\"},{\"name\":\"Manufacturer\",\"value\":\"UttamRobotics\"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"India\"},{\"name\":\"Manufacturer\",\"value\":\"\"},{\"name\":\"Packer Details\",\"value\":\"\"}]}]",
                "return_policy": "",
                "product_category": "124,300",
                "product_options": "[]",
                "size": "",
                "color": "",
                "brand": "253",
                "product_upload_date": "2023-01-05 10:36:54",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "31.51",
                "end_date": "2023-02-28",
                "start_date": "2023-01-30",
                "republic_day": "0",
                "shipping_charges": "",
                "deal_of_the_day": "1",
                "cash_on_delivary": "2",
                "salient_features": "",
                "product_salient": "{\"salient\":\"\",\"salient2\":\"\",\"salient3\":\"\",\"salient4\":\"\",\"salient5\":\"\"}",
                "freqvently_bought": "",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            },
            {
                "pid": "1378",
                "user_id": null,
                "seller_id": "83",
                "store_id": "38",
                "productid": "e7e765cadb0dfedac85552e7e5a831ab",
                "product_name": "Kemei KM-329 Professional Hair Straightener 40W (Multicolour) -1 pcs",
                "product_slug": "kemei-km-329-professional-hair-straightener-40w-multicolour-1-pcs",
                "product_sku": "Kemei-Hair-Straightener",
                "product_price": "899",
                "product_sale_price": "399",
                "product_stock": "98",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>Heavy duty and maintenance free</p>\r\n<p>This hair straightener from Kemei gives you salon-like sleek and straight hair without having to put them through blow-drying, that in many instances, absorbs moisture from your hair strands. Use this straightening rod instead, and style your hair from wet to dry, and frizzy to straight, in a matter of a few minutes.</p>\r\n<p><strong>Quick Operation</strong><br />You don&rsquo;t have to plug this straightener into the power socket hours or minutes before using it, as it has a quick heat up time of 30 seconds only.</p>\r\n<p><strong>Customised Operation</strong><br />You can operate this device at four different levels of temperatures. The long swivel cord ensures flexibility as well as ease and comfort while using this appliance.</p>\r\n<p><strong>Features of the Plates</strong><br />This straightening device is outfitted with special ceramic plates that can handle a good number of hair strands at a time without sticking to your hair.</p>\r\n<p><strong>Safety</strong><br />There is an LED indicator that signals whether the device is on/off. The device also shuts off automatically when the plates are heated to the desired temperature.</p>",
                "product_images": "assets/product_image/734b909447ef3b8b3ebda046ef3fffcd.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"Kemei\"},{\"name\":\"Model\",\"value\":\"Km-329\"},{\"name\":\"Manufacturer\",\"value\":\"Kemei Electronics\"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"China\"},{\"name\":\"Manufacturer\",\"value\":\"\"},{\"name\":\"Packer Details\",\"value\":\"\"}]}]",
                "return_policy": "",
                "product_category": "118,212",
                "product_options": "[]",
                "size": "",
                "color": "",
                "brand": "254",
                "product_upload_date": "2023-01-05 10:47:56",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "55.62",
                "end_date": "2023-01-16",
                "start_date": "2023-01-30",
                "republic_day": "0",
                "shipping_charges": "",
                "deal_of_the_day": "1",
                "cash_on_delivary": "0",
                "salient_features": "",
                "product_salient": "{\"salient\":\"\",\"salient2\":\"\",\"salient3\":\"\",\"salient4\":\"\",\"salient5\":\"\"}",
                "freqvently_bought": "",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            },
            {
                "pid": "1410",
                "user_id": null,
                "seller_id": "82",
                "store_id": "37",
                "productid": "35b285ed95af8d21c76afc8734bd92fa",
                "product_name": "ANT ESPORTS H707 HD RGB LED GAMING HEADSET",
                "product_slug": "ant-esports-h707-hd-rgb-led-gaming-headset",
                "product_sku": "H707 RGB 7.1 USB",
                "product_price": "1610",
                "product_sale_price": "1279",
                "product_stock": "0",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>The Ant Esports H707 HD RGB led gaming headset offer immersive surround sound for all the explosive action of your favourite games.</p>\r\n<ul>\r\n<li>Virtual Surround Sound with Zero Delay game communication.</li>\r\n<li>Enjoyable immersive game world with 7.1 virtual surround sound with 50 mm drivers.</li>\r\n<li>Durable Headband &ndash; high Quality materials used, Breathable &amp; soft comfort for Pre long your gaming session.</li>\r\n<li>Multiple platform.</li>\r\n<li>Military Quality Cable with high durability.</li>\r\n<li>Broad Compatibility with 3.5mm plug works on PC ( Windows XP/ 7/8/8.1/10), PS4, X box One, Nintendo 3DS , Laptop, PSP , Tablet , I pad, Mobile Phone.</li>\r\n</ul>",
                "product_images": "assets/product_image/bfa3ba846fa5a152b0aee83f617e4318.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"Ant Esports\"},{\"name\":\"Model\",\"value\":\"H707 RGB\"},{\"name\":\"Manufacturer\",\"value\":\"Ant Esports\"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"China\"},{\"name\":\"Manufacturer\",\"value\":\"Ant Esports\"},{\"name\":\"Packer Details\",\"value\":\"\"}]},{\"heading\":\"Warranty\",\"options\":[{\"name\":\"Warranty\",\"value\":\"1 Year\"}]}]",
                "return_policy": "",
                "product_category": "120,146,121,206",
                "product_options": "[]",
                "size": "",
                "color": "",
                "brand": "243",
                "product_upload_date": "2023-01-25 05:39:54",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "20.56",
                "end_date": "2023-02-28",
                "start_date": "2023-01-30",
                "republic_day": "0",
                "shipping_charges": "",
                "deal_of_the_day": "1",
                "cash_on_delivary": "0",
                "salient_features": "",
                "product_salient": "{\"salient\":\"Speaker Size- 50mm\",\"salient2\":\"Frequency- 20Hz-20Khz\",\"salient3\":\"7.1 Virtual Surround Sound\",\"salient4\":\"Military Quality Cable\",\"salient5\":\"Broad Compatibility with 3.5mm plug\"}",
                "freqvently_bought": "",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            },
            {
                "pid": "1584",
                "user_id": null,
                "seller_id": "148",
                "store_id": "87",
                "productid": "cf880158827bb42feb98b484a283be59",
                "product_name": "Musical Car Toys for Kids 360 Degrees Rotating Transparent Concept Car with Flashing 3D Light & Sound Toys for Kids 1-4 Years-Multicolour",
                "product_slug": "musical-car-toys-for-kids-360-degrees-rotating-transparent-concept-car-with-flashing-3d-light-and-sound-toys-for-kids-1-4-years-multicolour-916a795e3d07a6a72f700b8690ca3281",
                "product_sku": "",
                "product_price": "11499",
                "product_sale_price": "499",
                "product_stock": "50",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<ul class=\"a-unordered-list a-vertical a-spacing-mini\">\r\n<li><span class=\"a-list-item\">Toyz 360 Degree Rotating Transparent Concept Racing Car with 3D Flashing Led Light .Multifunctional,colorful lighting, clone gear mechanical system, awesome sound effects.</span></li>\r\n<li><span class=\"a-list-item\">Transparent Design. Can view the gear inside, help child to know mechanical concept earlier.</span></li>\r\n<li><span class=\"a-list-item\">Gear driving effect. Enhance Brain Development and build Child’s Curiosity for New Things. Different Color helps childr cognitive ability.</span></li>\r\n<li><span class=\"a-list-item\">Made from heavy-duty plastic, the toy has no small parts to it so that children can enjoy it. To operate toy car you need to have 3 x AA batteries (Not Included).</span></li>\r\n<li><span class=\"a-list-item\">This would be the best gift ever to give for little kids. They will enjoy watching the dancing car with all his delightful features. Great to give as a Birthday Gift, Holiday or Christmas</span></li>\r\n</ul>",
                "product_images": "assets/product_image/194b0204e140f23320e01b998593062f.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"Samadhan Store\"},{\"name\":\"Model\",\"value\":\"Musical Car Toys\"},{\"name\":\"Manufacturer\",\"value\":\"Imported\"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"India\"},{\"name\":\"Manufacturer\",\"value\":\"nill\"},{\"name\":\"Packer Details\",\"value\":\"Samadhan World\"}]},{\"heading\":\"Warranty\",\"options\":[{\"name\":\"Warranty\",\"value\":\"nill\"}]},{\"heading\":\"Technical Details\",\"options\":[{\"name\":\"Assembly Required\",\"value\":\"NO\"}]}]",
                "return_policy": "",
                "product_category": "121,196",
                "product_options": "[]",
                "size": null,
                "color": null,
                "brand": "100",
                "product_upload_date": "2023-04-26 16:04:23",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "0",
                "end_date": "2023-06-16",
                "start_date": "2023-05-17",
                "republic_day": "0",
                "shipping_charges": "30",
                "deal_of_the_day": "1",
                "cash_on_delivary": "0",
                "salient_features": "",
                "product_salient": "{\"salient\":\"360 Degrees Rotating Transparent Concept Car \",\"salient2\":\"Colorful lighting\",\"salient3\":\"Latest design\",\"salient4\":\"Trending and attractive Toy\",\"salient5\":\"\"}",
                "freqvently_bought": "",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            },
            {
                "pid": "1912",
                "user_id": null,
                "seller_id": "32",
                "store_id": "9",
                "productid": "26298c268ff3705d8a0a98411fc64e17",
                "product_name": "Water Sensor shivling Smokeless Sensor LED Light (Pack of 2) for Indoor and Outdoor Festival Decoration Light (Black & Red) SHIVLING Water Sensor",
                "product_slug": "water-sensor-shivling-smokeless-sensor-led-light-pack-of-2-for-indoor-and-outdoor-festival-decoration-light-black-and-red-shivling-water-sensor-93b5e9a1191a40f5ad59f323da4bc2e3",
                "product_sku": "SLight",
                "product_price": "399",
                "product_sale_price": "95",
                "product_stock": "991",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>Introducing our remarkable LED Water Sensor Lights, a brilliant addition to enhance the ambiance of any space. These lights are not only aesthetically pleasing but also in perfect working condition, promising a hassle-free and enjoyable experience. Crafted with precision and care, these lights are designed to add a touch of elegance and tranquility to your surroundings.</p>\r\n<p> </p>\r\n<p>Crafted from durable plastic, our Water Sensor Shivling Light Stands ensure safety and convenience with their smoke-free and flameless operation. This innovative design guarantees a worry-free and sustainable option for those special moments. No need to worry about open flames or melting wax; our lights offer both safety and beauty in one package.</p>\r\n<p> </p>\r\n<p>These lights are perfect for a wide range of occasions, making them incredibly versatile. Whether you're celebrating a birthday, indulging in a romantic candlelight dinner, setting the mood for a low-key ambiance, hosting a housewarming party, commemorating an anniversary, elevating the atmosphere of your office desk, or enhancing the ambiance of a hotel or restaurant, our LED Water Sensor Lights are the ideal choice.</p>\r\n<p> </p>\r\n<p>The versatility of these lights extends to their suitability for various settings. Whether you wish to create a serene tabletop waterfall indoors, add a touch of magic to your outdoor space, or elevate the ambiance of an anniversary celebration in your living room or garden, our lights are a perfect fit. Additionally, they can be used for home decoration, infusing your surroundings with an enchanting glow that radiates warmth and beauty.</p>\r\n<p> </p>\r\n<p>Enhance your environment with our LED Water Sensor Lights, designed to elevate your decor and create a soothing atmosphere. Their adaptability, safety features, and impeccable working condition make them the perfect choice for a variety of occasions and settings. Illuminate your life with these exceptional lights, and let them transform your space into a haven of tranquility and charm.</p>",
                "product_images": "assets/product_image/46dbd4cf5fe9b33544207c4fd71a2745.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"Others\"},{\"name\":\"Model\",\"value\":\"LED Sensor\"},{\"name\":\"Manufacturer\",\"value\":\"Luis Mercosl\"},{\"name\":\"Waterproof\",\"value\":\"Yes\"},{\"name\":\"Light Source Type\",\"value\":\"LED\"},{\"name\":\"Material\",\"value\":\"Plastic\"},{\"name\":\"Controller Type\",\"value\":\"Push Button\"},{\"name\":\"Mounting Type\",\"value\":\"Tabletop\"},{\"name\":\"Number of Items\",\"value\":\"2\"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"India\"},{\"name\":\"Manufacturer\",\"value\":\"Luis Mercosl\"},{\"name\":\"Packer Details\",\"value\":\"\"}]},{\"heading\":\"Warranty\",\"options\":[{\"name\":\"Warranty\",\"value\":\"NA\"}]}]",
                "return_policy": "",
                "product_category": "127,391",
                "product_options": "[]",
                "size": "",
                "color": "",
                "brand": "100",
                "product_upload_date": "2023-11-01 06:40:45",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "76.19",
                "end_date": "2023-11-30",
                "start_date": "2023-11-01",
                "republic_day": "0",
                "shipping_charges": "",
                "deal_of_the_day": "1",
                "cash_on_delivary": "0",
                "salient_features": "",
                "product_salient": "{\"salient\":\"Safety and Convenience\",\"salient2\":\"Indoor and Outdoor Use\",\"salient3\":\"Elegant Home Decoration\",\"salient4\":\"Highly versatile and suitable for a wide range\",\"salient5\":\"Lights are in a working condition\"}",
                "freqvently_bought": "1914,1915,1916",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            },
            {
                "pid": "1973",
                "user_id": null,
                "seller_id": "258",
                "store_id": "151",
                "productid": "3293880ee66ad6e3a624f2cff79625e5",
                "product_name": "CROMPTON ELECTRIC HEATER ( IMMERSION ROD ) 1000WATT 2 YEAR WARRANTY",
                "product_slug": "crompton-electric-heater-immersion-rod-1000watt-2-year-warranty--7fb657bd5fa67ca5419ae4ad98efe530",
                "product_sku": "CEWHIR1000W",
                "product_price": "950",
                "product_sale_price": "650",
                "product_stock": "5",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>Product Name  :- Electric Water Heater  ( Immersion Rod )</p>\r\n<p>Specification :- 1000Watt. 230V AC 50Hz</p>\r\n<p>Consumers Care Toll Free Number </p>\r\n<p>18004190505</p>\r\n<p>E-Mail I'd:- consumers.support@crompton.co.in</p>\r\n<p>Website :- www.crompton.co.in</p>",
                "product_images": "assets/product_image/27652949a75d18e7d915539ae8b6d3d3.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"CROMPTON \"},{\"name\":\"Model\",\"value\":\"WATER HEATER ( IMMERSION ROD )\"},{\"name\":\"Manufacturer\",\"value\":\"CROMPTON GREAVES CONSUMER ELECTRICALS LIMITED \"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"India\"},{\"name\":\"Manufacturer\",\"value\":\"CROMPTON GREAVES CONSUMER ELECTRICALS LIMITED \"},{\"name\":\"Packer Details\",\"value\":\"CROMPTON GREAVES CONSUMER ELECTRICALS LIMITED \"}]},{\"heading\":\"Warranty\",\"options\":[{\"name\":\"Warranty\",\"value\":\"2 Year\"}]}]",
                "return_policy": "",
                "product_category": "126,187",
                "product_options": "[]",
                "size": null,
                "color": null,
                "brand": "116",
                "product_upload_date": "2023-10-21 19:10:10",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "0",
                "end_date": "2023-12-31",
                "start_date": "2023-11-20",
                "republic_day": "0",
                "shipping_charges": "40",
                "deal_of_the_day": "1",
                "cash_on_delivary": "2",
                "salient_features": "",
                "product_salient": "{\"salient\":\"Light Weight\",\"salient2\":\"Heating Element With Longer Life\",\"salient3\":\"Shockproof Plastic Handle \",\"salient4\":\"Water Level Indicator \",\"salient5\":\"Powerful Heating Element \"}",
                "freqvently_bought": "",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            },
            {
                "pid": "1984",
                "user_id": null,
                "seller_id": "258",
                "store_id": "151",
                "productid": "5a881f086350044dab05f489ec91e9f2",
                "product_name": "HALONIX PRIME DJ SPEAKER BULB SOUND + COLORFUL LIGHT 9 WATT LED BULB 1 YEAR WARRANTY ",
                "product_slug": "halonix-prime-dj-speaker-bulb-sound-colorful-light-9-watt-led-bulb-1-year-warranty--eef31edafe8ec570d4617c2ca1cbea8b",
                "product_sku": "HPDJSB9WATT",
                "product_price": "1000",
                "product_sale_price": "850",
                "product_stock": "2",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>STEP TO CONNECT YOUR SMARTPHONE WITH HALONIX DJ SPEAKER BULB </p>\r\n<p>1) Please the DJ Speaker Bulb in the holder and Switch it on. </p>\r\n<p> </p>\r\n<p>2) Switch on the Bluetooth on your smartphone. </p>\r\n<p> </p>\r\n<p>3) Search the device ( Halonix DJ Speaker Bulb  ) on your smartphone and pair your Halonix DJ Speaker Bulb. </p>\r\n<p> </p>\r\n<p>4) You may need to pair your smartphone with the device every time the device is switched on.</p>\r\n<p>        STEP TO DIM THE LIGHT WHILE YOUR.                                    SPEAKER IS ON </p>\r\n<p> </p>\r\n<p>1) If your Halonix DJ Speaker Bulb is Switched on, switch off and switch on the bulb within 3 seconds .</p>\r\n<p> </p>\r\n<p>2) The Bulb will glow in 0.5W,  indicating that your speaker is on.</p>\r\n<p> </p>\r\n<p>3) Now you can play your favorite music. </p>",
                "product_images": "assets/product_image/477ed9682ad31a8ea3b8775f89ad69bf.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"HALONIX\"},{\"name\":\"Model\",\"value\":\"PRIME DJ SPEAKER BULB \"},{\"name\":\"Manufacturer\",\"value\":\"Halonix Technologies Pvt Ltd \"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"India\"},{\"name\":\"Manufacturer\",\"value\":\"HALONIX TECHNOLOGIES PVT LTD \"},{\"name\":\"Packer Details\",\"value\":\"Halonix Technologies Pvt Ltd \"}]},{\"heading\":\"Warranty\",\"options\":[{\"name\":\"Warranty\",\"value\":\"1 Year\"}]}]",
                "return_policy": "",
                "product_category": "117,227",
                "product_options": "[]",
                "size": null,
                "color": null,
                "brand": "28",
                "product_upload_date": "2023-10-25 13:10:41",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "0",
                "end_date": "2023-12-31",
                "start_date": "2023-11-20",
                "republic_day": "0",
                "shipping_charges": "40",
                "deal_of_the_day": "1",
                "cash_on_delivary": "2",
                "salient_features": "",
                "product_salient": "{\"salient\":\"Clear & Powerful Speaker \",\"salient2\":\"Millions of Colors\",\"salient3\":\"Bluetooth plus App Based\",\"salient4\":\"LUMEN 900lm (6500K)\",\"salient5\":\"Speaker Output 5W\"}",
                "freqvently_bought": "",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            },
            {
                "pid": "1985",
                "user_id": null,
                "seller_id": "261",
                "store_id": "154",
                "productid": "b81532edba99f8bda91136600465e378",
                "product_name": "ECONOMICAL MINI Domestic Mixer Grinding Machine 3 Stainless Steel Jars with 500 Watts Motor Champ",
                "product_slug": "economical-mini-domestic-mixer-grinding-machine-3-stainless-steel-jars-with-500-watts-motor-7c1f28d52e4229f3c91aebd1986018c3",
                "product_sku": "",
                "product_price": "2899",
                "product_sale_price": "1899",
                "product_stock": "99",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>Introducing our Economical Mini M.G. Series Watts 500, a Domestic Mixer Grinding Machine that combines power, efficiency, and durability in a compact design. Here's what makes it stand out:</p>\r\n<p> </p>\r\n<p><strong>Key Features:</strong></p>\r\n<ol>\r\n<li>\r\n<p><strong>Powerful and Quiet Operation:</strong> The 500 Watts motor ensures high-performance grinding while operating quietly, making it perfect for your daily kitchen needs.</p>\r\n</li>\r\n<li>\r\n<p><strong>Durable Construction:</strong> Built with a top-grade heat-resistant ABS body kit, this mixer grinder is designed to withstand regular use. The improved jar base fitting with a lock system enhances stability during operation.</p>\r\n</li>\r\n<li>\r\n<p><strong>Versatile Stainless Steel Jars:</strong> Comes with three stainless steel jars – a 1.25 Ltr liquidizing jar, a 0.9 Ltr dry grinding jar, and a 0.3 Ltr multi wet grinding jar. The jars, along with the pulse function, cater to various grinding and blending requirements.</p>\r\n</li>\r\n<li>\r\n<p><strong>Safety First:</strong> Equipped with an overload protection circuit breaker, this mixer grinder prioritizes your safety by preventing damage from power surges.</p>\r\n</li>\r\n<li>\r\n<p><strong>Reliable and Efficient:</strong> The 100% copper winding motor operates in an incredible range of 12000-18000 RPM, ensuring efficient grinding of ingredients. Plus, it comes with a 12-month warranty, guaranteeing a reliable performance</p>\r\n</li>\r\n</ol>\r\n<p> </p>\r\n<p>Upgrade your kitchen with the Economical Mini M.G. Series Watts 500 Mixer Grinder – an ideal choice for both efficiency and affordability. Whether you're grinding spices or blending smoothies, this mixer grinder delivers consistent results every time. Order yours now and experience the convenience of effortless grinding and blending!</p>",
                "product_images": "assets/product_image/ee5e31c3bd4e4c789720e26a0497c7a0.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"DIAMOND GOLD\"},{\"name\":\"Model\",\"value\":\"Champ\"},{\"name\":\"Manufacturer\",\"value\":\"DIAMOND GOLD\"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"India\"},{\"name\":\"Manufacturer\",\"value\":\"DIAMOND GOLD\"},{\"name\":\"Packer Details\",\"value\":\"DIAMOND GOLD\"}]},{\"heading\":\"Warranty\",\"options\":[{\"name\":\"Warranty\",\"value\":\"1 Year\"}]},{\"heading\":\"Technical Specifications\",\"options\":[{\"name\":\"Power Supply\",\"value\":\"230V AC only, 50 Hz\"},{\"name\":\"Input\",\"value\":\" 500 Watts\"},{\"name\":\"Rating\",\"value\":\"30 Minutes (05 min. On then 02 min. OFF)\"},{\"name\":\"R.P.M\",\"value\":\"18,000 approx\"},{\"name\":\"Class\",\"value\":\"1 Appliances\"},{\"name\":\"Insulation\",\"value\":\"Class-E\"}]}]",
                "return_policy": "",
                "product_category": "126,187",
                "product_options": "[]",
                "size": null,
                "color": null,
                "brand": "481",
                "product_upload_date": "2023-10-25 13:10:05",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "0",
                "end_date": "2023-12-31",
                "start_date": "2023-11-20",
                "republic_day": "0",
                "shipping_charges": "100",
                "deal_of_the_day": "1",
                "cash_on_delivary": "2",
                "salient_features": "",
                "product_salient": "{\"salient\":\"High-Performance Motor\",\"salient2\":\"Durable Construction\",\"salient3\":\"Versatile Stainless Steel Jars\",\"salient4\":\"Safety Assurance\",\"salient5\":\"Reliable Performance\"}",
                "freqvently_bought": "",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            },
            {
                "pid": "2076",
                "user_id": null,
                "seller_id": "267",
                "store_id": "152",
                "productid": "d3afe7cdf97d78ec85893a6619c3931a",
                "product_name": "Hindware Marvia 60 Auto Clean Chimney Wall Mounted Chimney",
                "product_slug": "hindware-marvia-60-934492b1dc09f981e5833d7fc6e3617c",
                "product_sku": "",
                "product_price": "13490",
                "product_sale_price": "7800",
                "product_stock": "99",
                "vendor_stock": "0",
                "product_weight": "0",
                "product_length": "0",
                "product_width": "0",
                "product_height": "0",
                "product_description": "<p>Introducing the Hindware Marvia 60 Wall Mount Kitchen Chimney – Your Ultimate Kitchen Companion!</p>\r\n<p>Elevate your kitchen experience with the Hindware Marvia 60, a sophisticated and efficient kitchen chimney that combines stunning design with powerful functionality. Crafted by the renowned brand Hindware, this kitchen chimney is designed to transform your cooking space into a sleek and stylish culinary haven.</p>\r\n<p>Key Features:</p>\r\n<ol>\r\n<li>\r\n<p><strong>Premium Black Finish:</strong> The Marvia 60 boasts a pyramid design with a premium black finish, adding a touch of elegance to your kitchen décor. It's not just a kitchen appliance; it's a statement piece.</p>\r\n</li>\r\n<li>\r\n<p><strong>Ideal Size:</strong> With a 60cm size, this chimney is perfectly suited for 2-3 burner stoves. It efficiently captures and eliminates smoke and odors, leaving your kitchen fresh and clean.</p>\r\n</li>\r\n<li>\r\n<p><strong>High Suction Capacity:</strong> Featuring a robust 900 m3/hr suction capacity, this chimney effortlessly handles medium to heavy frying and grilling. Say goodbye to lingering cooking smells and smoky air.</p>\r\n</li>\r\n<li>\r\n<p><strong>Efficient Baffle Filter:</strong> The double baffle filter system ensures that your kitchen remains free of oil and grease particles. These filters are easy to clean and maintain, ensuring your chimney operates at peak performance.</p>\r\n</li>\r\n<li>\r\n<p><strong>User-Friendly Controls:</strong> The push button control panel makes operating the chimney a breeze. You can effortlessly adjust the fan speed and lighting with just a touch.</p>\r\n</li>\r\n<li>\r\n<p><strong>Dual LED Lamps:</strong> The Marvia 60 is equipped with energy-efficient dual LED lamps that illuminate a wider surface, providing you with a well-lit cooking area for your culinary adventures.</p>\r\n</li>\r\n<li>\r\n<p><strong>Warranty:</strong> Rest easy with a 1-year warranty on the product and an impressive 5-year warranty on the motor, giving you peace of mind and assurance of long-lasting performance.</p>\r\n</li>\r\n</ol>\r\n<p>Upgrade your kitchen with the Hindware Marvia 60 Wall Mount Kitchen Chimney and enjoy a smoke-free, odor-free cooking environment. It's not just a kitchen appliance; it's a style statement and a testament to your commitment to a clean and modern kitchen.</p>\r\n<p>Enhance your culinary journey – order the Hindware Marvia 60 today and experience the difference!</p>",
                "product_images": "assets/product_image/46b8c9eb257f6b12120be7f8c25feaee.jpg",
                "add_info": "",
                "add_information": "[{\"heading\":\"Basic Details\",\"options\":[{\"name\":\"Brand\",\"value\":\"Hindware \"},{\"name\":\"Model\",\"value\":\" Marvia 60\"},{\"name\":\"Manufacturer\",\"value\":\"Hindware \"}]},{\"heading\":\"Manufacturer Details\",\"options\":[{\"name\":\"Country Of Origin\",\"value\":\"India\"},{\"name\":\"Manufacturer\",\"value\":\"Hindware\"},{\"name\":\"Packer Details\",\"value\":\"Hindware \"}]},{\"heading\":\"Warranty\",\"options\":[{\"name\":\"Warranty\",\"value\":\"1 Year\"},{\"name\":\"Motor\",\"value\":\"5 Year\"}]},{\"heading\":\"Technical Details\",\"options\":[{\"name\":\"Mounting Type\",\"value\":\"Wall Mount\"},{\"name\":\"Suction Capacity\",\"value\":\"900 m3/hr\"},{\"name\":\"Control Type\",\"value\":\" Push Button\"},{\"name\":\"Item Dimensions (LxWxH)\",\"value\":\"47.5 x 60 x 52 Centimeters\"},{\"name\":\"Chimney Size\",\"value\":\" 60cm\"},{\"name\":\"Filter Type\",\"value\":\"Double Baffle Filter\"}]}]",
                "return_policy": "",
                "product_category": "126,185",
                "product_options": "[]",
                "size": null,
                "color": null,
                "brand": "193",
                "product_upload_date": "2023-11-03 17:11:40",
                "product_tag": "",
                "type": "0",
                "best_selling": "0",
                "best_selling_color": "0",
                "feat_prod": "0",
                "discount": "0",
                "end_date": "2023-12-31",
                "start_date": "2023-11-20",
                "republic_day": "0",
                "shipping_charges": "100",
                "deal_of_the_day": "1",
                "cash_on_delivary": "2",
                "salient_features": "",
                "product_salient": "{\"salient\":\"Premium Black Finish\",\"salient2\":\"High Suction Capacity\",\"salient3\":\"Easy-to-Maintain Baffle Filter\",\"salient4\":\"User-Friendly Push Button Control\",\"salient5\":\"Dual LED Lamps\"}",
                "freqvently_bought": "",
                "product_services": "",
                "gst": "0",
                "product_status": "1",
                "product_reject": "",
                "meta_keyword": "",
                "meta_decs": "",
                "live": "0"
            }
        ]
    }

    const Suggestion = {
        "name": "Suggestions for you",
        "id": 10,
        "items": [
            {
                "pid": "2284",
                "productid": "756bfd8ba3e99668aea86417f0286555",
                "product_name": "SELVO 30A TPN Metal Clad Protected Three Pin Industrial Plug and Socket",
                "product_images": "assets/product_image/1aec846d2bd25d7a7d7b777eb7683679.jpg",
                "product_price": "900",
                "product_sale_price": "537",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "322"
            },
            {
                "pid": "3301",
                "productid": "045b0830e433ff77b5f62d46b60a7adb",
                "product_name": "330A TRIPOD, Professional Lightweight Aluminum Portable Tripod Stand 3 Way Head For Digital Camera Camcorder",
                "product_images": "assets/product_image/ae42616b9b88d750de6431050bb2622b.jpeg",
                "product_price": "1499",
                "product_sale_price": "550",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "526"
            },
            {
                "pid": "314",
                "productid": "30ef085c5bd525eacd85bc87ddfa9863",
                "product_name": "Apple iPhone 6s (Colour Gold, 32 GB)",
                "product_images": "assets/product_image/713faab76796368f8a643b3870290abd.png",
                "product_price": "29990",
                "product_sale_price": "7599",
                "discount": "74.66",
                "salient_features": "<ul>\r\n<li>Refurbished - Superb' condition</li>\r\n<li>Dual Core Processor</li>\r\n<li>Powerful 1715 mAh Battery</li>\r\n<li>Just Like New</li>\r\n<li>6 Month Warranty</li>\r\n</ul>",
                "color": "",
                "brand": "19"
            },
            {
                "pid": "1960",
                "productid": "5f4de1b90f86ca923495e28ffe8d27cf",
                "product_name": "EXOTIC Domestic Mixer Grinding Machine 3 Stainless Steel Jars with 750 Watts Motor Camry Metallic Gold",
                "product_images": "assets/product_image/c3c8685762391ca63b7b294040f5652c.jpg",
                "product_price": "5999",
                "product_sale_price": "5999",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "481"
            },
            {
                "pid": "3125",
                "productid": "c3224fbb894643ea4e26d028aaba8bee",
                "product_name": "Bike Mobile Holder with Waterproof Charger for Yahma Mt 15",
                "product_images": "assets/product_image/bdb955b50ed2632b551bcb6fb57497f0.jpeg",
                "product_price": "1499",
                "product_sale_price": "345",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "513"
            },
            {
                "pid": "2827",
                "productid": "3fe997f9364b21f6efc20ee6ecf894e3",
                "product_name": "Anchor By Panasonic 22046 6A Spike Guard with 4 Socket, 1 Switch, 1.5 Mtr (White & Blue) 4 Socket Extension Boards",
                "product_images": "assets/product_image/0087c20e42e34dc900b4e138434c356f.jpg",
                "product_price": "755",
                "product_sale_price": "480",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "89"
            },
            {
                "pid": "2386",
                "productid": "c2419d9a895111f85fa60ebb23f5a9b5",
                "product_name": "SELVO 4 Pole Metal Box & C-40A FP MCB ( COMBO OFFER )",
                "product_images": "assets/product_image/719a8b3d9d2028753b26ae1669bd9731.jpg",
                "product_price": "800",
                "product_sale_price": "769",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "322"
            },
            {
                "pid": "222",
                "productid": "b3d3412d4ac300e5f433af9bcf635cd9",
                "product_name": "Teslaa 3 in 1 Nylon Braided Fast Multi Charger Cable for Micro USB, iOS and Type-C Devices, 1M (RED)",
                "product_images": "assets/product_image/5d3cbfd1d864b2443f20c4b52ab40ca8.png",
                "product_price": "1049",
                "product_sale_price": "478",
                "discount": "54.43",
                "salient_features": "<ul>\r\n<li><span class=\"a-list-item\">2.4A Charge for 3 Devices</span></li>\r\n<li><span class=\"a-list-item\">IOS Cable + Micro Cable + USB C cable</span></li>\r\n<li><span class=\"a-list-item\">High Nickel Interface</span></li>\r\n</ul>",
                "color": "",
                "brand": "44"
            },
            {
                "pid": "561",
                "productid": "80850daf6f2cc82736cc2fc8d3420c1c",
                "product_name": "Xiaomi Mi A1 4 GB, 64 GB Refurbished (Gold)",
                "product_images": "assets/product_image/ddec6ac0204ebec83724893853e60f3d.jpg",
                "product_price": "14999",
                "product_sale_price": "4995",
                "discount": "66.7",
                "salient_features": "<ul>\r\n<li>Dual Primary Camera 12 MP&nbsp;</li>\r\n<li>HD video recording</li>\r\n<li>Android 7.1.2 Nougat</li>\r\n<li>Snapdragon 625 octa core processor 2 GHz</li>\r\n<li>Hybrid Dual SIM&nbsp;</li>\r\n<li>Sensors Fingerprin</li>\r\n</ul>",
                "color": "",
                "brand": "15"
            },
            {
                "pid": "976",
                "productid": "6ba801b26bc1ed146be878ae123c5131",
                "product_name": "Anchor by Panasonic XL Premium 14068TSL 1200mm Ceiling Fan Anti Dust (Titanium Silver)",
                "product_images": "assets/product_image/c84c2865c7fc98d8cf0ef4e934d73c87.jpg",
                "product_price": "2910",
                "product_sale_price": "2690",
                "discount": "7.56",
                "salient_features": "<ul class=\"a-unordered-list a-vertical a-spacing-mini\">\r\n<li><span class=\"a-list-item\"> Powerful Motor with Silent Operation </span></li>\r\n<li><span class=\"a-list-item\">Anti-Dust Coating Helps Easy Cleaing of Fans</span></li>\r\n<li><span class=\"a-list-item\">Pre-Greased Double Ball Bearings</span></li>\r\n<li><span class=\"a-list-item\">Wider Tip Baldes for Effective Ait Circulation</span></li>\r\n</ul>",
                "color": "",
                "brand": "89"
            }
        ]
    }

    const Recommended = {
        "name": "Recommended Products",
        "id": 6,
        "items": [
            {
                "pid": "3444",
                "productid": "6bc3e66f386b23d235ea1073bc8f1755",
                "product_name": "Wireless Retro Game Console Nostalgia Plug and Play Video Game Console 4k,40+ Emulators Console,64GB Built in 10000+ Video Games 2.4G Wireless Controllers",
                "product_images": "assets/product_image/440e8014d11fbd92bfb52b45c662c8fe.webp",
                "product_price": "5999",
                "product_sale_price": "2799",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "526"
            },
            {
                "pid": "2180",
                "productid": "fa70ae831f74d3735f2de9eaaa5f928d",
                "product_name": "Selvo C-10A Single Pole Flush Mounted (Screw Mounted) Mini MCB  (Pack of 6)",
                "product_images": "assets/product_image/6436da4b004fd46c17d7c9c8d8973ef7.jpg",
                "product_price": "800",
                "product_sale_price": "484",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "322"
            },
            {
                "pid": "2366",
                "productid": "bf08557f4cf80ba7e73ccaca3387bfd3",
                "product_name": "SELVO 32A 6 WAY TPN FUSE DISTRIBUTION BOARD",
                "product_images": "assets/product_image/b344b00ab0e38753ac8aaffe669aac3a.jpg",
                "product_price": "8950",
                "product_sale_price": "5368",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "322"
            },
            {
                "pid": "1435",
                "productid": "2cd68b9ca91b8f7b78c4c887c0c96e28",
                "product_name": "Automatic Portable Commercial Quick Ice Cube Maker 2 cm size for Restaurant, Hotel, Bar, Juice shop etc. ICE MATIIC IM-36",
                "product_images": "assets/product_image/d7365f73e31cac29ab46dd1a3fda662d.jpg",
                "product_price": "53500",
                "product_sale_price": "49560",
                "discount": "7.36",
                "salient_features": "",
                "color": "",
                "brand": "241"
            },
            {
                "pid": "1839",
                "productid": "a8d26268febc313f56bdf2fa259af21b",
                "product_name": "Leather Earphone Case - Cover Drop- Proof Anti- Scratch Charging Earphones Shell for Storage Pro Headphones Leather Bag Portable Accessories Light Case Brown",
                "product_images": "assets/product_image/40de9826277bed5ebdd5ee6a7762bb80.jpg",
                "product_price": "899",
                "product_sale_price": "250",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "100"
            }
        ]
    }

    const advertisementsData = {
        name: "Advertisment",
        id: 7,
        items: [
          {
            id: "1",
            brand_id: "2",
            title: "Advertisement 1",
            image: "assets/slider/ab10dca1ed771da5121c08e65abdf5ca.png",
            sponsored_by: "Kayroo",
            tags: "music, headphone",
            created_at: "2022-02-14 06:24:30",
          },
          {
            id: "2",
            brand_id: "4",
            title: "Advertisement 2",
            image: "assets/slider/863f739c221c80ac626bbcec7aebe7f9.png",
            sponsored_by: "Hammer",
            tags: "smartwatch",
            created_at: "2022-02-14 06:24:33",
          },
        ],
      };


      const newArival= {
        "name": "New Arrival",
        "id": 11,
        "items": [
            {
                "pid": "3452",
                "productid": "a9bfe1172356f0fa91f2cb9cf0e5361a",
                "product_name": "DY09 Universal Mobile Radiator Game Cooler System Cooling Fan RGB | For PUBG Gamepad Trigger Accessories",
                "brand": "",
                "product_description": "<p>1) Turbine exhaust technology for quickly dissipating the mobile phone heat.</p>\r\n<p> </p>\r\n<p>2) Low noise operation, does not interfere with voice chat, frequency conversion DC motor, stable wind for better use.</p>\r\n<p> </p>\r\n<p>3) The cooler is small and convenient, whose size is about one-third of the size of the mobile phone, making gaming perfect.</p>\r\n<p> </p>\r\n<p>4) Retractable buckle design, for all smart mobile phones.</p>\r\n<p> </p>\r\n<p>5) Frequency conversion DC motor, wind stable, no jitter, fan high-speed rotation at the same time, low noise operation</p>",
                "cash_on_delivery": "0",
                "end_date": null,
                "republic_day": "0",
                "product_stock": "99",
                "deal_of_the_day": "0",
                "product_images": "assets/product_image/8ada9567696fe18650bd936eaf69f3aa.jpeg",
                "product_slug": "dy09-universal-mobile-radiator-game-cooler-system-cooling-fan-rgb-for-pubg-gamepad-trigger-accessories-e44eba72552f64a134469f4c49541a56",
                "product_tag": "",
                "product_price": "2999",
                "product_sale_price": "829",
                "product_category": "121,444",
                "size": null,
                "color": null,
                "discount": "0",
                "product_image": "assets/product_image/8ada9567696fe18650bd936eaf69f3aa.jpeg",
                "category": ""
            },
            {
                "pid": "3451",
                "productid": "be851b93468731341bc6454ec351e5d3",
                "product_name": "Mobile Phone Cooler DY56 Mobile Phone Radiator Portable Fan Holder USB",
                "brand": "",
                "product_description": "<p><span class=\"a-list-item\">RAPID COOLING DOWN - With the dual engine, It's the same refrigeration principle as the refrigerator, not the ordinary fan cooling，it can cool down your phone in 3s to avoid overheat and ensure stabilize your live streaming or gaming experience.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">DUAL MUTE DISSIPATION - Dual silent designing fan can efficiently emit wind from all sides, providing a stronger refrigeration effect, no disturbance to your gaming or your Vlog show.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">ADVANCED COOLING TECHNOLOGY - Cell Phone Cooler adopts the newest semiconductor refrigeration radiator technology that can cool your devices instantaneously, keeping your mobile device at the optimal temperature without screen dims, heat sinks, freezes or automatic shutdown due to high temperatures, and preventing its performance from being compromised. You are able to feel and see the performance boost with the featured live temperature display.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">ULTRA QUIET - The mobile phone radiator adopts a 35db noise reduction design. It’s silent and won’t impact your game play or movie watching marathons. Compact, lightweight design, and RGB LEDs embedded beneath the fan bring you a greater style and gaming immersion no matter where you are.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">UNIVERSAL COMPATIBILITY - Our phone cooling fan is designed to be compatible with all type smartphone and width range is from 6 to 9cm. To use, simply clamp it to the back of your device and you are ready to immerse yourself in long gaming sessions.</span></p>",
                "cash_on_delivery": "0",
                "end_date": null,
                "republic_day": "0",
                "product_stock": "99",
                "deal_of_the_day": "0",
                "product_images": "assets/product_image/3de936f5233a53dc0f2351a0059bcd79.jpg",
                "product_slug": "mobile-phone-cooler-dy56-mobile-phone-radiator-portable-fan-holder-usb-7cc426e26a964902ffa910a5c60aecff",
                "product_tag": "",
                "product_price": "2999",
                "product_sale_price": "799",
                "product_category": "121,444",
                "size": null,
                "color": null,
                "discount": "0",
                "product_image": "assets/product_image/3de936f5233a53dc0f2351a0059bcd79.jpg",
                "category": ""
            },
            {
                "pid": "3450",
                "productid": "83878ece42110d8884b7187c78469248",
                "product_name": "DY66 Mobile Phone Cooling Fan Universal Phone Cooler Smartphone Cooler For Mobile Phone Processor Cooler",
                "brand": "",
                "product_description": "<p>READY TO USE, ANYWHERE: Plug and play convenience is at your fingertips with this phone cooler for gaming. The included 3.3ft charging cable provides ample maneuverability, ensuring flexibility in your setup. Compatible with all smartphones ranging from 4.5 to 7 inches, simply attach this mobile cooling fan to the back of your device, plug in the power cable, and get ready to embark on exhilarating gaming sessions.</p>\r\n<p> </p>\r\n<p>Try our phone cooler gaming fan and elevate your gaming experience today.EASY INSTALLATION, VERSATILE USAGE: Enjoy the convenience of the clamp design that effortlessly attaches the gaming mobile cooler fan to the back of your phone, allowing you to continue using your device without any hassle. Compatible with most 4.5-7 inch Android and iOS smartphones, this cooling fan enhances your phone's performance during gaming sessions.</p>\r\n<p> </p>\r\n<p>Lightweight and portable, it is the perfect companion for mobile gamers on the go.ENJOY LONG GAMING SESSIONS: Keep your phone cool while gaming or live streaming with this high-performance phone cooler gaming fan. Designed for mobile gamers, bloggers, and streamers, it effectively cools your device in seconds, preventing overheating and ensuring optimal performance for extended periods. Say goodbye to worrying about your phone's temperature and immerse yourself in uninterrupted gaming sessions like never before.</p>\r\n<p> </p>\r\n<p>SILENT AND STYLISH: Say goodbye to noisy phone cooling fans that distract you from your gameplay or movie marathons. This mobile cooler radiator features a 35db noise reduction design, ensuring a peaceful environment while keeping your phone cool. The compact and lightweight design, combined with the stylish blue LEDs beneath the fan, adds a touch of flair to your gaming setup. Protect your phone from overheating and excessive use in silence and style.</p>\r\n<p> </p>\r\n<p>INSTANT COOLING TECHNOLOGY: Experience the power of semiconductor refrigeration radiator technology with this phone cooler for gaming. Equipped with a powerful turbo fan, it cools your phone in an instant, eliminating heat-related issues and blackouts during intense mobile gaming sessions. Choose between two working speeds to enhance cooling performance or prioritize quiet operation while maximizing energy efficiency. Take full control over your gaming experience</p>",
                "cash_on_delivery": "0",
                "end_date": null,
                "republic_day": "0",
                "product_stock": "99",
                "deal_of_the_day": "0",
                "product_images": "assets/product_image/145f4d6041abda119262541dd4cb0178.jpg",
                "product_slug": "dy66-mobile-phone-cooling-fan-universal-phone-cooler-smartphone-cooler-for-mobile-phone-processor-cooler-b37fe9734d959068bf51d32a505dc728",
                "product_tag": "",
                "product_price": "2999",
                "product_sale_price": "850",
                "product_category": "121,444",
                "size": null,
                "color": null,
                "discount": "0",
                "product_image": "assets/product_image/145f4d6041abda119262541dd4cb0178.jpg",
                "category": ""
            },
            {
                "pid": "3449",
                "productid": "8d92c5ac81ffeac39a4157244cae3a29",
                "product_name": "Hybite Full Metal Body Bike & Scooty 360 Degree Rotating Mobile Holder Stand for Bicycle, Motorcycle, Scooty Fits All Smartphones Multicolor",
                "brand": "",
                "product_description": "<p><span class=\"a-list-item\">This Bike Phone Holder body is made of premium aluminum alloy material. Durable and touch struture can securely hold the phone even on the uneven and bad road conditions.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">360° Adjustable: You can adjust your cell phone in any angle and direction within 360 degree horizontally and 120 degree vertically, free your hands at any time and anywhere.(Please tighten the screws firmly before riding.)</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">Eagle claw design, with cushioning stickers, will not scratch your phone, shockproof and non-slip, can hold your mobile phone tightly.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">The clean and clever jaw-grip design sports great holding power without hiding your smartphone behind foam pads and silicon bands.</span></p>",
                "cash_on_delivery": "0",
                "end_date": null,
                "republic_day": "0",
                "product_stock": "99",
                "deal_of_the_day": "0",
                "product_images": "assets/product_image/99e704bbd34d1609d504dc0f6f3b57c3.jpg",
                "product_slug": "hybite-full-metal-body-bike-and-scooty360-degree-rotating-mobile-holder-stand-for-bicycle-motorcycle-scooty-fits-all-smartphones-multicolor-c2-a7a5041c952a611c59c43c2e42cea8e6",
                "product_tag": "",
                "product_price": "999",
                "product_sale_price": "299",
                "product_category": "102,160",
                "size": null,
                "color": null,
                "discount": "0",
                "product_image": "assets/product_image/99e704bbd34d1609d504dc0f6f3b57c3.jpg",
                "category": ""
            },
            {
                "pid": "3448",
                "productid": "330da8fbe32f1491f64e2d08e9cc637a",
                "product_name": "Universal Bike C1 Mobile Holder Metal Body 360 Degree Rotating Handlebar Stand for Bicycle, Motorcycle, Fits All Smartphones Easy Adjustable (Metal Holder with USB Charger)",
                "brand": "",
                "product_description": "<p><span class=\"a-list-item\">Firm and 100% Reliable: Aluminium mobile phone rack + mechanical lock by screw + rod fixing ring locked by long scews on handlebar to make your phone 100% steady and anti-shake even when riding on rocky roads; IP66 waterproof plastic cover on USB makes riding easy and safe in light rain.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">All Aluminium Alloy: the motorcycle phone mount made from all aluminium alloy to make it firmer and safer on handlebar/ rear-view mirror; whole set aluminium alloy design and fine workmanship make it looks high-end.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">360 Degree Rotation and Flexible: 360° rotatable design to make your phone freely adjusted to any angles; phone width adjuster screw nut on mobile phone rack side to make the handlebar phone holder flexibly adjusted to fit for all 4.0-6.0inch smartphones.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">Wide Compacbility: 10-24V output from motorcycle battery with 9.6cm max. width to charge/fit for all 4-6 inch cellphones. eg. iPhone XS/XS Max/XR/8/8P/ Samsung S9/S9+/S8/S8+/Huawei/more...; it can be mounted on all 22-30mm handlebars of ATV/ Sled Car/ Motorcycles.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">Quick Charge USB3.0 Max 3.4A Output: Qualcomm QC. 3.0 motorcycle handlebar phone bracket, with USB super fast charging interface, can charge your QC smartphones at its fastest possible speed up to 3.4A 24W(max.).</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">This Bike Phone Holder body is made of premium aluminum alloy material. Durable and touch struture can securely hold the phone even on the uneven and bad road conditions.</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">Easy to Install: Using our complete mini tool makes phone holder easier mount to your bike or motorcycle, just simply attach to the handlebar and locked with a screw, secure your phone on it then you good to go!</span></p>\r\n<p> </p>\r\n<p><span class=\"a-list-item\">Aluminium Alloy Material with Sponge,The metal phone mount will hold your cell phone tightly on the bicycle, the Sponge also protect your cell phone.</span></p>",
                "cash_on_delivery": "0",
                "end_date": null,
                "republic_day": "0",
                "product_stock": "99",
                "deal_of_the_day": "0",
                "product_images": "assets/product_image/39f8edbba2c38e0b9734a94e5b70c859.jpg",
                "product_slug": "universal-bike-c1-mobile-holder-metal-body-360-degree-rotating-handlebar-stand-for-bicycle-motorcycle-fits-all-smartphones-easy-adjustable-metal-holder-with-usb-charger-977f8fa51759bf2f58b64e3d48ffcd74",
                "product_tag": "",
                "product_price": "999",
                "product_sale_price": "329",
                "product_category": "102,160",
                "size": null,
                "color": null,
                "discount": "0",
                "product_image": "assets/product_image/39f8edbba2c38e0b9734a94e5b70c859.jpg",
                "category": ""
            },
            {
                "pid": "3447",
                "productid": "f0191c0a0dbcf29abf696e72b76b06f0",
                "product_name": "MZ M423SP (PORTABLE HOME TV SOUNDBAR) Dynamic Thunder Sound 2400mAh Battery 10 W Bluetooth Soundbar",
                "brand": "",
                "product_description": "<p>MZ M423SP - Sound Bar Dynamic Thunder Sound with High Bass 10 W Bluetooth Speaker. let you to enjoy your music anywhere indoor/outdoor. You can match it to your style quotient Portable Wireless Speaker. Easy to operate; with volume and play/pause buttons for convenience. Support all wireless devices connected., Soft, clear and dynamic sound all levels clear, Support line in audio input, provide you with computer speakers can be connected to mobile phone tablet computer and TV wireless pairing playing music. High Bass Sound Quality.</p>\r\n<p> </p>\r\n<p>Wireless Bluetooth Streaming Wirelessly stream high-quality stereo sound from your Smartphone or tablet. TF CARD TF Card Music Player: Built-in TF card read-only decoding can play TF card stored in MP3 / WMA format music directly Easy Connect Bluetooth is a short-range wireless communication technology that is both robust and energy efficient. The technology allows easy wireless connection to Bluetooth devices, such as smart phones, tablets or even laptops. Easy to Operate Bluetooth. Built-in Mic helps you to seamlessly talk on sound bar while connected.</p>",
                "cash_on_delivery": "0",
                "end_date": null,
                "republic_day": "0",
                "product_stock": "99",
                "deal_of_the_day": "0",
                "product_images": "assets/product_image/33522d36baec52b757b641a9c701d2fb.jpg",
                "product_slug": "mz-m423sp-portable-home-tv-soundbar-dynamic-thunder-sound-2400mah-battery-10-w-bluetooth-soundbar-cafb4b57067be389fc8d69af0c58b71b",
                "product_tag": "",
                "product_price": "2999",
                "product_sale_price": "699",
                "product_category": "120,147",
                "size": null,
                "color": null,
                "discount": "0",
                "product_image": "assets/product_image/33522d36baec52b757b641a9c701d2fb.jpg",
                "category": ""
            }
        ]
    }

    const moreProduct = {
        "name": "More Products",
        "id": 12,
        "items": [
            {
                "pid": "155",
                "productid": "14ee08935f87e1904ee4d88e9bd94159",
                "product_name": "KAYROO Mobile Battery for Nokia 3310 / Lumia 225 ( 4UL ), 1450 mAh Battery",
                "product_images": "",
                "product_price": "449",
                "product_sale_price": "199",
                "discount": "55.68",
                "salient_features": "<ul>\r\n<li>Compatible with BL-4UL</li>\r\n<li>Battery Power 1450mAh</li>\r\n<li>Long Life</li>\r\n</ul>",
                "color": "",
                "brand": "2"
            },
            {
                "pid": "1086",
                "productid": "b85921c18f8214bb0bbd86616e9646ac",
                "product_name": "TP Troops 4600mAh Power Bank TP1041",
                "product_images": "assets/product_image/6ea5338510c2d554bdd654b3f12bb12a.jpg",
                "product_price": "699",
                "product_sale_price": "285",
                "discount": "59.23",
                "salient_features": "<ul>\r\n<li>Fast Charging</li>\r\n<li>Long Life</li>\r\n<li>Powerful 4600mAh</li>\r\n</ul>",
                "color": "",
                "brand": "11"
            },
            {
                "pid": "2199",
                "productid": "0e8e963a0791bd50c74e14e30456cad5",
                "product_name": "SELVO C-32A Three Pole MCB",
                "product_images": "assets/product_image/8000c1fd8f6ca1d94d8f9c58650ac64a.jpg",
                "product_price": "660",
                "product_sale_price": "402",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "322"
            },
            {
                "pid": "1386",
                "productid": "8d40d0396c74c869fc73e7bfe2ef7b4c",
                "product_name": "Rasoi Galaxy Neptune Stainless Steel 2 Burner Gas Stove, Silver (ISI Certified)",
                "product_images": "assets/product_image/a066375e7f0682ae4a7e9ec873076d1e.jpg",
                "product_price": "5600",
                "product_sale_price": "1659",
                "discount": "70.38",
                "salient_features": "",
                "color": "",
                "brand": "255"
            },
            {
                "pid": "1826",
                "productid": "2d07df64d96577a2a7ad7117a34f1c09",
                "product_name": "Charger Cable Saver, Silicone Flexible Cable Wire Protector, Mouse Cable Protector, Suit for All Cellphone Data Lines (12pack)",
                "product_images": "assets/product_image/7c1d22c7cbd383594c8105d44fcd39c7.jpg",
                "product_price": "299",
                "product_sale_price": "50",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "100"
            },
            {
                "pid": "1475",
                "productid": "b368fdb7e4548a35780e5a9288688e27",
                "product_name": "Elak MX-50 Automatic Motorcycle VRLA Battery Charger",
                "product_images": "assets/product_image/436f3b519b46a0aa021c66934f383042.jpg",
                "product_price": "12910",
                "product_sale_price": "10478",
                "discount": "0",
                "salient_features": "",
                "color": null,
                "brand": "306"
            }
        ]
    }
            
    


  return (
    <>
        <div>
            <Header />
      <Slideshow />
        <ProductCardContainer heading={productData.name} products={productData.items} />
        <ProductCardContainer heading={Recommended.name} products={Recommended.items} />
        <BrandAdSection />
        
        <ProductCardContainer heading={Suggestion.name} products={Suggestion.items} />
        <ProductCardContainer heading={newArival.name} products={newArival.items} />
        <ProductCardContainer heading={moreProduct.name} products={moreProduct.items} />

        </div>
        <Footer />
    </>
  )
}

export default Home
